platform :ios, '13.0'

target 'BlessingChannel' do
  use_frameworks!
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'GoogleSignIn', '~>6.2.0'
  pod 'naveridlogin-sdk-ios'
  pod 'Google-Mobile-Ads-SDK'

  target 'BlessingChannelTests' do
    inherit! :search_paths
  end

  target 'BlessingChannelUITests' do
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end

