# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BlessingChannel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlessingChannel
    pod 'KakaoSDKCommon'
    pod 'KakaoSDKAuth'
    pod 'KakaoSDKUser'
    pod 'GoogleSignIn'
    pod 'GTMAppAuth'
    pod 'GTMSessionFetcher'

  target 'BlessingChannelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlessingChannelUITests' do
    # Pods for testing
  end

end
